# Generated by Django 3.2 on 2021-05-29 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('date', models.DateTimeField()),
                ('content', models.TextField(max_length=96000)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='serwisInf.article', unique=True)),
                ('avg', models.DecimalField(decimal_places=2, max_digits=3)),
                ('rating_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=128)),
                ('content', models.TextField(max_length=2048)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwisInf.article')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='topic_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serwisInf.topic'),
        ),
    ]
